import test, { expect } from '@playwright/test'

test("Create Lead",async({page})=>{

    await page.goto("http://leaftaps.com/opentaps/control/main")
    await page.getByRole("textbox",{name:'Username'}).fill('Demosalesmanager')
    await page.getByText("Password").fill('crmsfa')
    await page.getByRole("button",{name:'Login'}).click()
    await page.waitForTimeout(3000)
    await page.getByRole("link",{name:'CRM/SFA'}).click()
    await page.getByRole("link",{name:'Leads'}).click()
    await page.waitForTimeout(3000)
    await page.getByRole("link",{name:'Create Lead'}).click()
    await page.locator("//input[@id='createLeadForm_companyName']").fill('TestLeaf')
    await page.locator("//input[@id='createLeadForm_firstName']").fill('Vaidy')
    await page.locator("//input[@id='createLeadForm_lastName']").fill('K')
    await page.locator("//input[@id='createLeadForm_personalTitle']").fill('Mr')
    await page.locator("//input[@id='createLeadForm_generalProfTitle']").fill('Mr')
    await page.locator("//input[@id='createLeadForm_annualRevenue']").fill('10000000')
    await page.locator("//input[@id='createLeadForm_departmentName']").fill('QA')
    await page.locator("//input[@id='createLeadForm_primaryPhoneNumber']").fill('1234567890')
    await page.waitForTimeout(3000)
    await page.locator("//input[@class='smallSubmit']").click()
    await page.waitForTimeout(3000)

    //Auto-Retry
    console.log("Auto-Retry")
    await expect(page.locator("#viewLead_companyName_sp")).toContainText("TestLeaf")
    await expect.soft(page.locator("#viewLead_firstName_sp")).toContainText("Vaidy")
    await expect(page.locator("#viewLead_lastName_sp")).toContainText("K")
    await expect(page.locator("#viewLead_statusId_sp")).toContainText("Assigned")
    await page.waitForTimeout(3000)

    //Non-Retry
    // console.log("Non-Retry")
    // const cmp = page.locator("#viewLead_companyName_sp")
    // const fn = page.locator("#viewLead_firstName_sp")
    // const ln = page.locator("#viewLead_lastName_sp")
    // const st = page.locator("#viewLead_statusId_sp")
    // expect(cmp).toBe('TestLeaf')
    // expect(fn).toBe("Vaidy")
    // expect(ln).toBe("K")
    // expect(st).toBe("Assigned")
    // await page.waitForTimeout(3000)
})