import test, { expect } from '@playwright/test'

test("Create New Account",async({page})=>{
    await page.goto("https://login.salesforce.com/")
    await page.getByLabel("Username").fill('dilipkumar.rajendran@testleaf.com')
    await page.getByLabel("Password").fill('TestLeaf@2025')
    await page.locator("//input[@id='Login']").click()
    await page.waitForTimeout(2000)
    await expect(page).toHaveTitle('Home | Salesforce')
    await expect(page).toHaveURL('https://testleaf.lightning.force.com/lightning/page/home')
    await page.waitForTimeout(2000)
    await page.locator("[class='slds-icon-waffle']").click()
    await page.waitForTimeout(2000)
    await page.locator("//button[text()='View All']").click()
    await page.getByPlaceholder("Search apps or items...").fill('Service')
    await page.waitForTimeout(2000)
    await page.locator(".slds-app-launcher__tile-body.slds-truncate").first().click()
    await page.waitForTimeout(2000)
    await page.locator("[href='/lightning/o/Account/home']").click()
    await page.getByRole("button",{name:'New'}).click()
    await page.locator("[name='Name']").fill('Vaidy')
    await page.locator("//button[@name='SaveEdit']").click()
    await page.waitForTimeout(5000)
    await expect(page.locator('.forceToastMessage')).toContainText('was created')

})